### ISSUE TITLE
build issue with react-attributes?

### ISSUE THREAD

**Issue by th3fallen** [nitin42/animate-components#12]
@nitin42 

It appears im getting this with react-attributes which is published by you but i cant find a repo for it.

```ERROR in assets/js/vendor-f4077c28349e66b94f3a.js from UglifyJs
Unexpected token: name (shouldNotBeUndefined) [./~/react-attributes/index.js:3,0][assets/js/vendor-f4077c28349e66b94f3a.js:78808,4]
```

any ideas?

**Comment by th3fallen** [comment]
The issue is how you're exporting them

```
module.exports = {
  attributes,
  shouldNotBeUndefined,
};
```
should be
```
module.exports = {
  attributes: attributes,
  shouldNotBeUndefined: shouldNotBeUndefined,
};
```

otherwise uglify will fubar their names and break when you attempt to import them.

**Comment by th3fallen** [comment]
had to downgrade to 0.9.0 until i get this sorted 😢

**Comment by nitin42** [comment]
What are you looking for ? `react-attribute` package ? or is it related to the lib ?

**Comment by th3fallen** [comment]
it's from `react-attribute` which this lib uses

**Comment by nitin42** [comment]
I haven't push the code for the `react-attribute` on GitHub. But there should be no such errors as far as I am concern !?

**Comment by th3fallen** [comment]
anything over v0.9.0 wont build with uglify v1 is the first time that dep is introduced and the error is coming from a method in it so ¯\_(ツ)_/¯

**Comment by nitin42** [comment]
I am merging the code from that package into the lib and removing it as a dependency. I am gonna publish a new update. Can you wait for.. 20 minutes ?

**Comment by th3fallen** [comment]
i've already reverted but i'll reupdate and test the build then, just let me know.

**Comment by nitin42** [comment]
Great!

**Comment by nitin42** [comment]
Published `1.1.6`. Check and let me know !

**Comment by th3fallen** [comment]
That works! 🙇

**Comment by nitin42** [comment]
Changes - 

* containers refactored ([HOC.js](https://github.com/nitin42/animate-components/blob/master/src/containers/HOC.js) and [merge.js](https://github.com/nitin42/animate-components/blob/master/src/containers/merge.js))
* added eslint comments.
* removed `react-attributes` package.
* some other fixes

**Comment by nitin42** [comment]
Great again !
