### ISSUE TITLE
"generate-components" dependency

### ISSUE THREAD

**Issue by pattishin** [nitin42/animate-components#14]
It would be awesome to have `generate-components` installed with the `animate-components` module. Ran into a few hiccups just now and realized that module got updated a few hours ago.
Thanks in advance! 👍 😁

**Comment by nitin42** [comment]
I am working on some issues and would strongly recommend using v1.3.0 animate-components (which is stable) and I would upload generate-components soon!

**Comment by nitin42** [comment]
Install both the packages with the current version only until I land V2. Let me know how it goes!

**Comment by nitin42** [comment]
Fixed! There was a cyclic dependency issue so I'd to remove the package `generate-components`. Everything should be working now. I have published the new version on npm. Try installing it and let me know!

**Comment by pattishin** [comment]
Ty! It's working on my end. Awesome response time btw! 🙌

**Comment by nitin42** [comment]
Great!
