### ISSUE TITLE
Inferno support?

### ISSUE THREAD

**Issue by Meadowcottage** [nitin42/animate-components#16]
Are there any plans of adding support for [InfernoJS](https://infernojs.org/)?
Would be a nice addition if possible 😄 ❤️

**Comment by nitin42** [comment]
I'd earlier (it's in my list) but currently I am working on transitioning between the components. If things go well, I would land the support for InfernoJS!

**Comment by nitin42** [comment]
I haven't use InfernoJS. How's that different from React ? Any core primitives ?

**Comment by Meadowcottage** [comment]
Basically a lightweight React that's faster and smaller and as far as I have looked into it so far, a fair few of the core react components are the same in Inferno.
But I may be wrong 😕

**Comment by nitin42** [comment]
I tried Inferno and must say it has a great performance ! I ran a demo of `animate-components` with `Inferno-compat` and it worked but it gave me some strange errors. Seems like I will adding support for `Inferno` and 'Preact' in next release (already started working!)

**Comment by nitin42** [comment]
Published v1 for Inferno ! Try installing it and let me know.

```
npm install ac-inferno --save
```

The api is same (though I will be publishing the docs also soon)

**Comment by nitin42** [comment]
There is still some work to do but things should work for now. Expect a stable release soon !

Remaining - 

* Better error warnings
* Reduce build size
* Docs for some changes
* Code cleanup

**Comment by Meadowcottage** [comment]
Tested it a basic InfernoJS app and basic usage worked perfectly \o/
Sadly usage in a [electron-forge](https://github.com/electron-userland/electron-forge) inferno app doesn't work. Though I think the error is more to do with the community made InfernoJS template.
Seems to still be a react import in a electron module 😕 
```
C:\Users\Meadowcottage\Desktop\inferno\node_modules\electron-prebuilt-compi…dules\electron\dist\resources\electron.asar\common\reset-search-paths.js:1

Uncaught Error: Cannot find module 'react'
```

**Comment by nitin42** [comment]
Did you tried Inferno-compat and configuring your webpack ?

**Comment by nitin42** [comment]
I've tested everything from my side and it works !

**Comment by nitin42** [comment]
Resolving the aliases or resetting your webpack should work. I don't know much about the build process for electron framework.

**Comment by Meadowcottage** [comment]
Sadly the [electron-forge](https://github.com/electron-userland/electron-forge) system doesn't use webpack 😕 
Here's an example of the `electron-forge` file structure/setup: [github.com/owstat/owstat](https://github.com/owstat/owstat)

**Comment by nitin42** [comment]
Ok. I don't know much about electron-forge !

**Comment by nitin42** [comment]
Released the stable version for InfernoJs `ac-inferno@1.0.3`. Hope you find a solution for `electron-forge` !

**Comment by Meadowcottage** [comment]
So after testing it, I was able to get it working with `electron-forge` by adding react as a dev dependency.
So far that seems to be the only work around for the error that `electron-prebuilt-compile` is returning.

**Comment by nitin42** [comment]
Great!

**Comment by Meadowcottage** [comment]
If I find a way to get around having to add `react` as a dev dependency, then i'll reply to this thread letting you know :)

**Comment by nitin42** [comment]
Sure 😄
