### ISSUE TITLE
move react and react-dom to peer dependancies

### ISSUE THREAD

**Issue by th3fallen** [nitin42/animate-components#18]
Title says it all

**Comment by nitin42** [comment]
umm.. could you create a PR for that ? I'm a little busy with an another project so it may take a while to push the changes 😄

**Comment by th3fallen** [comment]
absolutely :)

**Comment by nitin42** [comment]
Thank you so much!!

**Comment by nitin42** [comment]
Update the build size when you run the webpack 👍

**Comment by th3fallen** [comment]
> Update the build size when you run the webpack 👍

need more coffee apparently, what you're asking went right over my head

**Comment by th3fallen** [comment]
![](http://th3fallen.d.pr/DJrmR.jpg) i "think" that's what you're asking for lol

**Comment by th3fallen** [comment]
PR made at https://github.com/nitin42/animate-components/pull/19

**Comment by nitin42** [comment]
Did you ran all the test and checked everything locally ?

**Comment by nitin42** [comment]
shouldn't break anything since everything is stable 😅

**Comment by th3fallen** [comment]
yep, it should make no difference what so ever for any end user, just lets those of us that want to use fiber beta use it without this lib pulling an older version.

**Comment by th3fallen** [comment]
could you do a tag so we can consume it? please/thanks

**Comment by nitin42** [comment]
Elaborate !

**Comment by th3fallen** [comment]
a release/tag so we can install via npm?

**Comment by nitin42** [comment]
umm.. you made changes to `package.json` which was in root, right ?

**Comment by nitin42** [comment]
No changes were made to `animate-components`.

**Comment by th3fallen** [comment]
am i mistaken, but i thought npm used tags to get versions which are based on particular commits?

**Comment by nitin42** [comment]
There were no changes to the core and this fix was for the `package.json` which was in root. So I think we don't require a new version.

**Comment by nitin42** [comment]
But still thanks for the changes 😄

**Comment by th3fallen** [comment]
anytime, but without even a patch version bump (x.x.1) no one can consume the changes via yarn/npm

**Comment by nitin42** [comment]
Ok I will publish the new version! Just give me some time.. a little busy here !

**Comment by th3fallen** [comment]
no worries, thanks again!

**Comment by nitin42** [comment]
Here you go - `✨   animate-components@1.4.3`

**Comment by nitin42** [comment]
Fixed some other issues as well (btwn you didn't notice them 😅 )
