### ISSUE TITLE
Demo site does not seem to work

### ISSUE THREAD

**Issue by winkler1** [nitin42/animate-components#2]
No errors, but blank page on https://nitin42.github.io/ac/

**Comment by nitin42** [comment]
Hi Jeff! It's in development will be up in an hour.

**Comment by nitin42** [comment]
The site is up !

**Comment by james2m** [comment]
Seems to be down again!

**Comment by nitin42** [comment]
It should be working. Here you go - http://animate-components.surge.sh/
