### ISSUE TITLE
Version Question

### ISSUE THREAD

**Issue by th3fallen** [nitin42/animate-components#22]
Per your releases page your latest version is 1.3.0 but npm shows latest at 1.4.5
https://www.npmjs.com/package/animate-components
https://github.com/nitin42/animate-components/releases

but version 1.4.5 (latest from npm) doesnt have the updated package.json that adds react and react-dom as peer deps

am i missing something?

**Comment by nitin42** [comment]
Need to change the project structure (this will address your issue).

**Comment by nitin42** [comment]
Done!
