### ISSUE TITLE
Disappear speed up animation?

### ISSUE THREAD

**Issue by th3fallen** [nitin42/animate-components#29]
I hope im just missing something but what's the best way to accelerate the animation in the disappear hoc?

**Comment by chocobuckle** [comment]
@th3fallen According to the docs you can pass a 'duration' prop... [Disapper Component](https://github.com/nitin42/animate-components/blob/master/packages/animate-components/docs/usage.md#user-content-disappear-component)

**Comment by th3fallen** [comment]
ahhh i thought that was how long it would stay displayed... im an idiot. thanks

**Comment by th3fallen** [comment]
actually, i need to figure out how to make stay displayed longer the 2s is perfect to disappear but it should show for longer :(

**Comment by chocobuckle** [comment]
If I understand you correctly, it sounds like the [Delay Component](https://github.com/nitin42/animate-components/blob/master/packages/animate-components/examples/delay.js) might be helpful?

**Comment by th3fallen** [comment]
Good call I'll try it out. Thanks
