### ISSUE TITLE
Add ability to change element type

### ISSUE THREAD

**Issue by th3fallen** [nitin42/animate-components#3]
By default you add a `span` but that causes issues with bootstrap v4 would be nice if we had the option to change it to say a `div` or something of the sorts...

**Comment by th3fallen** [comment]
or the ability to add classes to the span wrapper would work as well

**Comment by nitin42** [comment]
I am experimenting on this. It won't be appropriate to add classes to the wrapper (using styled-components keyframes)

**Comment by nitin42** [comment]
Haven't tried this with Bootstrap v4. Are you sure that it causes issues ?

**Comment by nitin42** [comment]
How about if we enclose it like this ?

```javascript
<div>
  <Bounce>
    <p>Hello</p>
  </Bounce>
</div>
```

**Comment by th3fallen** [comment]
It causes issues with notices particularly (only place i've used them thus far... but here's with it being inline-block'd vs block'd

inline block
http://th3fallen.d.pr/ygX2

block
http://th3fallen.d.pr/bFre


I had to wrap it in a div with a class so i could target the span and force it to display block

**Comment by th3fallen** [comment]
even if we couldnt add custom classes to it, a class to identify it would be super handy for this. atm there's no way to target that span without wrapping it.

**Comment by nitin42** [comment]
Ok. So what you are saying is that `HOC` should render the `props.children` inside a `<div>` wrapper instead of `span` which causes the display to be `inline`. Right ?

**Comment by nitin42** [comment]
That may target the children nodes to display block.

```javascript
<div {...this.state.styles}>
  {this.props.children}
</div>
```

**Comment by th3fallen** [comment]
yes that would solve it but may cause backwards compat issues for other users of the lib which is why i was originally asking for the option to change it with a prop could be as simple as 
```<Bounce block>
    <p>Hello</p>
  </Bounce>

**Comment by nitin42** [comment]
I think this would be better. Thanks !

**Comment by th3fallen** [comment]
anytime! thanks for the library, saves me so much pain, just wish i handled components transitioning out. :(

**Comment by nitin42** [comment]
May be I could land transitioning soon 😄

**Comment by nitin42** [comment]
Added support for rendering an animation component with prop `block`.  Check it out and let me know. I have also added an example in the [readme](https://github.com/nitin42/animate-components/blob/master/README.md)

**Comment by nitin42** [comment]
Let me know about its behaviour.

**Comment by nitin42** [comment]
Does `react-motion` try to solve **Component Transitioning** ? I've never used it before. Seems a little complex and full of abstraction.
