### ISSUE TITLE
can't use npm install

### ISSUE THREAD

**Issue by anakinjay** [nitin42/animate-components#4]
Some issue with the npm package... the latest version I'm able to install from NPM is 0.8.2

"No compatible version found: animate-components@0.9.5"

I've tried both NPM, and Yarn, and installing directly from github with npm install nitin42/animate-components

**Comment by nitin42** [comment]
Fixed it. There was an issue with an existing dependency version. Try installing again and let me know!

**Comment by anakinjay** [comment]
all good!  thank you much!

**Comment by nitin42** [comment]
👍
