### ISSUE TITLE
Yarn upgrade issue?

### ISSUE THREAD

**Issue by th3fallen** [nitin42/animate-components#6]
```
 ~/Sites/When-I-Work/wheniwork-js   feature/update-deps  yarn upgrade animate-components
yarn upgrade v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/animate-components/-/animate-components-1.1.4.tgz: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
info If you think this is a bug, please open a bug report with the information provided in "/Users/clarktomlinson/Sites/When-I-Work/wheniwork-js/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
``` 

getting this when trying to upgrade, is this an issue on your end or theirs?

**Comment by nitin42** [comment]
Hi there ! It should be working now. Please check

**Comment by th3fallen** [comment]
confirmed working thanks.

**Comment by nitin42** [comment]
Can you show me the part of your code where you are using `animate-components` ? Just curious to know how everyone is using the api.

**Comment by th3fallen** [comment]
Sure, here's  two components that use it

https://gist.github.com/th3fallen/6d36c4b702cd86e487bd3517e5c93bd0

**Comment by nitin42** [comment]
Hehe! New release will also bring performance improvements and reduce build size 😄

**Comment by nitin42** [comment]
Try this new prop - 

**[component prop](https://github.com/nitin42/animate-components/blob/master/docs/usage.md/#component)** 🔥
